Feature/backend get info
vlad9564/SCP-Interns-Project pull request #10
Opened 2019-11-04 11:52 UTC by GoseLegendarul

Created about endpoint.

2019-11-04 13:12 UTC, imartinas requested changes

2019-11-04 13:12 UTC, imartinas commented on backend/SCP-Interns-Project-Backend/src/main/java/com/cerner/SCPInternsProjectBackend/service/AboutService.java
> +		return mapper.readValue(getAboutFile(), AboutDto.class);
Put these two lines in one (22, 23).

2019-11-05 05:56 UTC, imartinas approved these changes

2019-11-05 07:07 UTC, razvanpan approved these changes

2019-11-05 10:44 UTC, merged