Feature/backend update patient
vlad9564/SCP-Interns-Project pull request #8
Opened 2019-11-04 11:27 UTC by andreibalau

Implementation for patient endpoint (PUT request)

- to be able to update a patient with a new doctor

2019-11-04 13:18 UTC, imartinas requested changes

2019-11-04 13:18 UTC, imartinas commented on backend/SCP-Interns-Project-Backend/src/main/java/com/cerner/SCPInternsProjectBackend/controller/PatientApi.java
>      }
Please remove the write to console lines.

2019-11-04 13:18 UTC, imartinas commented on backend/SCP-Interns-Project-Backend/src/main/java/com/cerner/SCPInternsProjectBackend/controller/PatientApiController.java
> +				System.out.println(servicePatient.updatePatient(patientId,body));
Please remove the write to console.

2019-11-04 13:18 UTC, imartinas commented on backend/SCP-Interns-Project-Backend/src/main/java/com/cerner/SCPInternsProjectBackend/service/PatientService.java
> +//		System.out.println(patient);
Remove commented line.

2019-11-04 13:18 UTC, imartinas commented on backend/SCP-Interns-Project-Backend/src/main/java/com/cerner/SCPInternsProjectBackend/controller/PatientApi.java
>      }
Please remove the write to console lines.

2019-11-05 10:42 UTC, imartinas approved these changes

2019-11-05 14:09 UTC, andreeacojocaru731 approved these changes

2019-11-05 14:14 UTC, merged